### ISSUE TITLE
Documentation is out of sync

### ISSUE THREAD

**Issue by omenSi** [root-11/tablite#112]
I think the `tablite` library is awesome in terms of handling large data. Thanks for the development efforts!

However, I noticed that rapid changes to the core elements made the documentation out of sync and at this moment completely misleading. 

Why? 

- *README.md* states, that `tablite` uses `h5py`, however, I can't seem to find anything related to it (only in the *requirements.txt*). 
- Some of the claims about RAM or disk usage may be outdated. I know `tablite` now use `numpy` as data storage.

There might be other things, but the frontpage is definitely the first thing that pops with outdated information.

**Comment by root-11** [comment]
README updated.
I'm adding API documentation as a github action
