### ISSUE TITLE
multi proc join

### ISSUE THREAD

**Issue by root-11** [root-11/tablite#118]
![image](https://github.com/root-11/tablite/assets/4048422/c69083d9-1066-4733-82df-098db484af58)

TODO: account for memory footprint.

**Comment by root-11** [comment]
Let's discuss this solution:

https://github.com/root-11/tablite/compare/master...memory_prediction

this includes:

- long running task manager so that subproc's aren't started again and again.
- disk based chunking of tasks so we shouldn't run out of RAM ever. If you do run out, reduce the pagesize in the config.
- nice portability of tasks to MPI.

@realratchet

**Comment by realratchet** [comment]
Seems fine, haven't tried running it. Only weird thing I noticed was this https://github.com/root-11/tablite/compare/master...memory_prediction#diff-c308236ef3ad023e5000bcad7c0fbdfa4d1f2bf53e50f1d0c145d0b427428817R1044 not exactly sure what this annotation is as I've never seen this. I assume you're trying to express Union here? If so then prior to 3.10 it's `typing.Union[dict, typing.NoneType]` in 3.10+ it can be expressed as `dict | typing.NoneType`.

**Comment by root-11** [comment]
Done in branch `constant_memory_footprint`
