### ISSUE TITLE
Columns with empty names

### ISSUE THREAD

**Issue by omenSi** [root-11/tablite#123]
Hello,

It may be my personal opinion, but it seems non logical to have table columns with empty names. 

Currently, `tablite` allows to have a column with an empty name (or just a whitespace).

I would expect to receive an exception telling me, that "column name cannot be empty".
```
>>> from tablite import Table
>>> t = Table()
>>> t[""] = [1, 2, 3]
>>> t.show()
+==+=+
|# | |
+--+-+
| 0|1|
| 1|2|
| 2|3|
+==+=+
```

**Comment by root-11** [comment]
@omenSi Table column names can also be tuples, so we ( @root-11 & @realratchet ) think the validation of column names should be left to the user. 

Will you be okay with that?

**Comment by omenSi** [comment]
I guess we will just have to deal with that on our end.
