### ISSUE TITLE
copy to clipboard would be nice.

### ISSUE THREAD

**Issue by ttopi** [root-11/tablite#2]
When I've created a nice table and want to paste the data into some visualisation package, it would be nice to be able to copy paste.

**Comment by root-11** [comment]
Copy to/from clipboard is supported from https://github.com/root-11/tablite/commit/77670906c198c908f9b4f8abda587267ae68a504

**Comment by root-11** [comment]
@ttopi please review, test and close.

**Comment by root-11** [comment]
Packaged as https://pypi.org/project/tablite/2020.11.3.59813/
Use `pip install tablite --upgrade --no-cache` to install.
