### ISSUE TITLE
sorting problem with datetime dt columns

### ISSUE THREAD

**Issue by cerv15** [root-11/tablite#71]
def test_sort_datetime():
    from datetime import datetime
    t = Table(columns={"A": [datetime(2019, 2, 2, 12, 12, 12), datetime.now()], "B": [2, 2]})

    t.sort({"A": False})
    # try:
    #     t.sort({"A": False})
    # except:
    #     t.show()
    #     print('datetime sort failed')        

    # from numpy import datetime64
    # t = Table(columns={"A": [datetime64('2005'), datetime64(datetime.now())], "B": [2, 2]})
    # try:
    #     t.sort({"A": False})
    # except:
    #     t.show()
    #     print('np.datetime sort failed')

**Comment by root-11** [comment]
Solved in #7d531c6 with version bump to 2023.6.dev13
