### ISSUE TITLE
Inconsistent row slice

### ISSUE THREAD

**Issue by realratchet** [root-11/tablite#77]
When slicing a table the result is inconsistent based on number of columns.

If more than 1 column exists `tbl[slice(...)]` will produce a new Tablite table from the original table for the given slice.
If table has exactly 1 column `tbl[slice(...)]` will produce a np.array from the only column  for the given slice.
If table has exactly 0 columns `tbl[slice(...)]` will produce an empty table.

I think the API not behave differently based on the table layout and should instead be consistent.

**Comment by root-11** [comment]
Please compare with the description in the tests. The behaviour is based on pythons own behaviour

**Comment by realratchet** [comment]
Not really sure I follow because python does not have such data structure, I'm assuming you mean list slicing vs list indexing, e.g., 
```
>>>[0, 1, 2, 3][slice(1, 2)] 
[1]

>>>[0, 1, 2, 3][1:2]
[1]

>>>[0, 1, 2, 3][1]
1
```
unless there's something else that I'm missing.

Personally, I feel operation results should be predictable blackbox based on input with the least amount of special rules. I can bite my teeth and fix the operation to deal with this special case when there's only a single column, but this will be the case for any operation that would deal with table slices and not columns individually.

**Comment by realratchet** [comment]
I changed for the behaviour for the moment to be more consistent, we can revert it back later if you have a better solution than having to change the operations to account for it or ducktyping it on import.
